ALTER TABLE tickets MODIFY COLUMN category ENUM(
  'BUG', 'MAINTENANCE', 'CLOUD_MAINTENANCE', 'DATABASE',
  'DEPLOYMENT_STAGING', 'DEPLOYMENT_PROD', 'FEATURE', 'HARDWARE', 'BREAK_FIX', 'IT_SUPPORT'
) NOT NULL;

ALTER TABLE client_rates MODIFY COLUMN category ENUM(
  'BUG', 'MAINTENANCE', 'CLOUD_MAINTENANCE', 'DATABASE',
  'DEPLOYMENT_STAGING', 'DEPLOYMENT_PROD', 'FEATURE', 'HARDWARE', 'MEETING', 'BREAK_FIX', 'IT_SUPPORT'
) NOT NULL;